version: '3'
services:
 # Define the API PHP application
  core:
    build: ./core
    restart: always
    ports:
     - "9000:80"

 # Define the redis NGINX forward proxy container
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - core