version: '3'
services:
 # Define the API PHP application
  core:
    # Build the Dockerfile that is in the web directory
    build: ./core
    restart: always

    #volumes:
    # - ./core:/home/core/app/web

    # Expose port 8080 to other containers (not to the host of the machine)
    ports:
     - "9000:80"

 # Define the redis NGINX forward proxy container
  nginx:
    # build the nginx Dockerfile: http://bit.ly/2kuYaIv
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - core