version: '3'
services:
 # Define the API PHP application
 ms-app:

   # Build the Dockerfile that is in the web directory
   build: web

   # Always restart the container regardless of the exit status; try and restart the container indefinitely
   restart: always

   # Expose port 8000 to other containers (not to the host of the machine)
   expose:
     - "8000"

   # Mount the web directory within the container at /home/ms-app/app/web
   volumes:
     - ./web:/home/ms-app/web

   # Don't create this container until the redis and postgres containers (below) have been created
   #depends_on:
    # - redis
    # - postgres

 # Define the redis NGINX forward proxy container
 nginx:

   # build the nginx Dockerfile: http://bit.ly/2kuYaIv
   build: nginx/
   restart: always

   # Expose port 80 to the host machine
   ports:
     - "80:80"
   deploy:
     mode: replicated
     replicas: 3

   # The Flask application needs to be available for NGINX to make successful proxy requests
   depends_on:
     - ms-app